### ISSUE TITLE
Problem with filenames in /etc/network/interfaces.d/

### ISSUE THREAD

**Issue by vv3** [mrlesmithjr/ansible-quagga#4]
When configuring loopback interfaces on Debian 8, the resulting file is named /etc/network/interfaces.d/lo:1.cfg. This file is not detected by ifup/ifdown on Debian. The man page for 'interfaces' states:
 "names must consist entirely of ASCII upper- and  lower-case  letters,  ASCII  digits, ASCII underscores, and ASCII minus-hyphens".
A valid filename could be 'lo_1'

**Comment by mrlesmithjr** [comment]
@vv3 Thanks for pointing this out, can you give it a try using branch `issue#4`?

**Comment by vv3** [comment]
On Thu, 21 Sep 2017 22:39:40 +0000 "Larry Smith Jr." <notifications@github.com> wrote:

> @vv3 Thanks for pointing this out, can you give it a try using branch `issue#4`?

Thanks for your prompt response. I took a quick look at the patch, and I
think it is not quite complete. The period also needs to be removed from
the filename.

The man-page states:

    "names must consist entirely of ASCII upper- and
     lower-case letters, ASCII digits, ASCII underscores, and ASCII
     minus-hyphens".

A valid filename could be 'lo_1'.

 - Vegard V -

**Comment by mrlesmithjr** [comment]
Thanks for catching that as well. Will be fixed here soon.

**Comment by mrlesmithjr** [comment]
@vv3 Ok this should be resolved now. I just validated with `Debian Jessie`.

**Comment by mrlesmithjr** [comment]
@vv3 We good to close this?

**Comment by vv3** [comment]
On Fri, 6 Oct 2017 04:45:55 +0000 "Larry Smith Jr." <notifications@github.com> wrote:

> @vv3 We good to close this?

Yes. Thanks for the fix.

-- 
- Vegard V -

**Comment by mrlesmithjr** [comment]
Awesome!
